include M4_MAKEFILES_DIR/Linux

CXXFLAGS   += M4_CXXFLAGS
LINKFLAGS  += M4_LDFLAGS
DYLIBFLAGS += M4_LDFLAGS
SHLIBFLAGS += M4_LDFLAGS
SYSLIBS     = -ldl -lrt

LINKMODE       := CUSTOM
DEFAULT_TARGET := shared_release
